name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose up -d

      - name: Run test
        run: echo "Test passed"

      - name: Tear down
        run: docker compose down -v --remove-orphans

      - name: Login to Docker registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Tag and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag miner-mike:latest ${{ secrets.DOCKER_REGISTRY }}/pipeline-push-image:nopush
          docker push ${{ secrets.DOCKER_REGISTRY }}/pipeline-push-image:nopush
